BC_PATH  = C:\BORLANDC
INC_PATH = $(BC_PATH)\INCLUDE
LIB_PATH = $(BC_PATH)\LIB

CC       = $(BC_PATH)\BIN\BCC.EXE
ASM      = $(BC_PATH)\BIN\TASM.EXE
LINKER   = $(BC_PATH)\BIN\TLINK.EXE

CFLAGS   = -ml -c -v -I$(INC_PATH) -Isrc -Isrc\work\misc -nbuild -w-par
LFLAGS   = /v /c /L$(LIB_PATH)

TARGET   = PACWARS.EXE
OBJS     = game\maze.obj game\mazeanim.obj game\spritgen.obj game\manedit.obj \
           game\mazeedit.obj game\mazespt.obj game\mazeutil.obj game\mazedraw.obj \
           game\mazecomm.obj game\mazeinit.obj game\mazereg.obj game\mvagraph.obj \
           game\home.obj game\disppic.obj game\meditstr.obj game\hiscore.obj \
           game\graph256.obj game\mem256.obj game\ipxc.obj game\ipxcomm.obj \
           game\utils.obj game\criterr.obj game\invokoff.obj game\qdispoff.obj \
           game\ext3_3.obj game\overlap.obj game\ipx.obj

all: $(TARGET)

$(TARGET): $(OBJS)
	$(LINKER) $(LFLAGS) @link.rsp

game\overlap.obj: src\overlap.asm
	$(ASM) /ml src\overlap.asm game\overlap.obj

game\ipx.obj: src\ipx.asm
	$(ASM) /ml src\ipx.asm game\ipx.obj

game\maze.obj: src\maze.c
	$(CC) $(CFLAGS) src\maze.c

game\mazeanim.obj: src\mazeanim.c
	$(CC) $(CFLAGS) src\mazeanim.c

game\spritgen.obj: src\spritgen.c
	$(CC) $(CFLAGS) src\spritgen.c

game\manedit.obj: src\manedit.c
	$(CC) $(CFLAGS) src\manedit.c

game\mazeedit.obj: src\mazeedit.c
	$(CC) $(CFLAGS) src\mazeedit.c

game\mazespt.obj: src\mazespt.c
	$(CC) $(CFLAGS) src\mazespt.c

game\mazeutil.obj: src\mazeutil.c
	$(CC) $(CFLAGS) src\mazeutil.c

game\mazedraw.obj: src\mazedraw.c
	$(CC) $(CFLAGS) src\mazedraw.c

game\mazecomm.obj: src\mazecomm.c
	$(CC) $(CFLAGS) src\mazecomm.c

game\mazeinit.obj: src\mazeinit.c
	$(CC) $(CFLAGS) src\mazeinit.c

game\mazereg.obj: src\mazereg.c
	$(CC) $(CFLAGS) src\mazereg.c

game\mvagraph.obj: src\mvagraph.c
	$(CC) $(CFLAGS) src\mvagraph.c

game\home.obj: src\home.c
	$(CC) $(CFLAGS) src\home.c

game\disppic.obj: src\disppic.c
	$(CC) $(CFLAGS) src\disppic.c

game\meditstr.obj: src\meditstr.c
	$(CC) $(CFLAGS) src\meditstr.c

game\hiscore.obj: src\hiscore.c
	$(CC) $(CFLAGS) src\hiscore.c

game\graph256.obj: src\graph256.c
	$(CC) $(CFLAGS) src\graph256.c

game\mem256.obj: src\mem256.c
	$(CC) $(CFLAGS) src\mem256.c

game\ipxc.obj: src\ipxc.c
	$(CC) $(CFLAGS) src\ipxc.c

game\ipxcomm.obj: src\ipxcomm.c
	$(CC) $(CFLAGS) src\ipxcomm.c

game\utils.obj: src\work\misc\utils.c
	$(CC) $(CFLAGS) src\work\misc\utils.c

game\criterr.obj: src\work\misc\criterr.c
	$(CC) $(CFLAGS) src\work\misc\criterr.c

game\invokoff.obj: src\work\misc\invokoff.c
	$(CC) $(CFLAGS) src\work\misc\invokoff.c

game\qdispoff.obj: src\work\misc\qdispoff.c
	$(CC) $(CFLAGS) src\work\misc\qdispoff.c

game\ext3_3.obj: src\work\misc\ext3_3.c
	$(CC) $(CFLAGS) src\work\misc\ext3_3.c

clean:
	del game\*.obj
	del game\*.map
	del game\pacwars.exe

